[package]
name = "io-algo-4-rna-stapmq"
version = "0.1.0"
authors = ["heartsh <heartsh@heartsh.io>"]
description = "\"io-algo-4-rna-stapmq\", Inside-outside Algorithm for RNA Structural-alignment Probability Matrix Quadruple"

[dependencies]
bio-seq-algos = "0.1"
rna-algos = "0.1"
itertools = "0.7"
lazy_static = "0.1"
time = "0.1"
scoped_threadpool = "0.1"
getopts = "0.2"
bio = "0.9"
num_cpus = "1.0"

[lib]
path = "src/lib.rs"
name = "io_algo_4_rna_stapmq"
