[package]
name = "stem"
version = "0.1.0"
authors = ["heartsh <heartsh@heartsh.io>"]
description = "STEM Program, Program for Approximate Expectation-maximization of RNA Structural-alignment Posterior Probabilities"

[dependencies]
# rna-algos = "0.1"
rna-algos = {path = "../rna-algos"}
itertools = "0.7"
lazy_static = "0.1"
time = "0.1"
scoped_threadpool = "0.1"
getopts = "0.2"
bio = "0.20"
num_cpus = "1.0"

[lib]
path = "src/lib.rs"
name = "stem"
